### ISSUE TITLE
私有API 调用错误 

### ISSUE THREAD

**Issue by cycmay** [btcdolab/btcdo-official-api-docs#1]
'{"error":"AUTH_SIGNIN_REQUIRED","data":null,"message":"No Authorization nor valid API signature."}'

但是request里面给了headers了啊 求教原因

**Comment by microljy** [comment]
API signature有错，我现在也没解决，感觉已经严格按照要求了，你解决了吗？

**Comment by cycmay** [comment]
还没解决 。。。

**Comment by microljy** [comment]
我用python的接口，里面API-KEY没大写，我就改了这个点

**Comment by cycmay** [comment]
然后就好使了？是键大写 还是值大写呢？

**Comment by microljy** [comment]
键，不过还是不行hh

**Comment by microljy** [comment]
会不会他们内部吧api关掉了，今天申请新的api key都不给我发邮件了

**Comment by cycmay** [comment]
我搞好了 兄弟 注意签名那 即便没有data也要写一行空白

**Comment by microljy** [comment]
不错哈！不过我还没搞定诶，兄弟方便帮我看下嘛？我基本用的是官方python的脚本，只把键改成大写。我签名的字符串是下面这个样子，path下一行的data我的确是有空行的，可是还是会报错。

```
GET
www.btcdo.com
/v1/trade/orders

API-KEY: AAAAAjt3i2PWFlzPofyLJ3lfFvHlTTxV
API-SIGNATURE-METHOD: HmacSHA256
API-SIGNATURE-VERSION: 1
API-TIMESTAMP: 1530368076333
```
Error:
```
b'{"error":"AUTH_SIGNIN_REQUIRED","data":null,"message":"No Authorization nor valid API signature."}'
```

**Comment by cycmay** [comment]
请访问api.btcdo.com 然后包装一下请求头的useragent部分

**Comment by microljy** [comment]
感谢！！之前对这方面不是很懂。现在可以啦！

**Comment by KingWangYang** [comment]
GET
api.btcdo.com
/v1/user/accounts

API-KEY: AAAAAkfg5LEQUZ69gM7usT4e1rjPN9Lm
API-SIGNATURE-METHOD : HmacSHA256
API-SIGNATURE-VERSION: 1
API-TIMESTAMP: 1531101617211
API-UNIQUE-ID: 0931f0a0e5bb454e9b9de60c2fe69bbc


我的是这样的为什么还是一直报

{"error":"AUTH_SIGNIN_REQUIRED","data":null,"message":"No Authorization nor valid API signature."}

**Comment by cycmay** [comment]
这样子的原因多半是没包装headers （如果最后的data没有也要空一行）

**Comment by KingWangYang** [comment]
空了。  我加密出来的sign是这个样子的  f1a95f6a13501f5e153cd7f439be90b7e9ecf8f016b7d38554cdf27275154352

**Comment by KingWangYang** [comment]
我用的是C#语言 
  public string HmacSHA256(string message, string secret)
        {
            using (var hmacsha256 = new HMACSHA256(Encoding.UTF8.GetBytes(secret)))
            {
                byte[] hashmessage = hmacsha256.ComputeHash(Encoding.UTF8.GetBytes(message));
                return UrlEncode(hashmessage);
            }
        }

        /// <summary>
        /// 转义字符串
        /// </summary>
        /// <param name="str"></param>
        /// <returns></returns>
        public string UrlEncode(byte[] hashmessage)
        {
            string pwd = "";
            for (int i = 0; i < hashmessage.Length; i++)
            {
                // 将得到的字符串使用十六进制类型格式。格式后的字符是小写的字母，如果使用大写（X）则格式后的字符是大写字符
                pwd = pwd + hashmessage[i].ToString("x");
            }
            return pwd.ToLower();
        }
我是这样加密的

**Comment by cycmay** [comment]
你确定包装了headers？错误提示是没有找到验证信息 我猜是过滤掉了你的请求 可能是官方对api访问有限制 解决方法就是模拟浏览器访问就行

**Comment by KingWangYang** [comment]
抓包工具显示请求头里有信息，但是还是报这个错误

**Comment by cycmay** [comment]
是重写user-agent

**Comment by KingWangYang** [comment]
headerDic.Add("Content-Type", "application/json");
            headerDic.Add("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36");
            headerDic.Add("Accept-Language", "zh-cn");

我是这样写的

**Comment by cycmay** [comment]
联系客服吧 我当初这个API遇到的错误只有 伪装请求头headers & 最后一行data不空

**Comment by KingWangYang** [comment]
您好，您知道客服的账号嘛？我找半天了，都没有找到

**Comment by cycmay** [comment]
。。。 多半是你自己的原因 我已经告诉你两处需要注意的地方了 其他的只能靠你自己了
